server:
  port: 80

spring:
  application: 
    name: microservicecloud-consumer-dept
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/#,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-consumer-dept7001      # 修改微服务名称
    prefer-ip-address: true                # 设置ip地址访问
    
feign:
  hystrix:
    enabled: true